from commands2 import Command, Subsystem
from commands2.sysid import SysIdRoutine
import math
from phoenix6 import SignalLogger, swerve, units, utils
from typing import Callable, overload
from wpilib import DriverStation, Notifier, RobotController, SmartDashboard, Timer
from wpilib.sysid import SysIdRoutineLog
from wpimath.geometry import Pose2d, Rotation2d

from pathplannerlib.auto import AutoBuilder
from pathplannerlib.config import RobotConfig, PIDConstants
from pathplannerlib.controller import PPHolonomicDriveController

from generated.tuner_constants import TunerSwerveDrivetrain
from handlers.limelight_helpers import (
    get_bot_pose_estimate_wpi_blue_megatag1,
    get_bot_pose_estimate_wpi_blue_megatag2,
    set_robot_orientation,
)
from constants.match import HUB_RESET_POSES
from constants.vision import (
    CON_VISION,
    VISION_MT1_MIN_TAGS,
    VISION_POSE_CORRECT_ENABLED,
    VISION_POSE_CORRECT_MODE,
    VISION_POSE_CORRECT_PERIOD_LOOPS,
    VISION_RESET_TIMEOUT,
)
from telemetry.vision_correct_logging import maybe_log_vision_correct
from telemetry.vision_reset_logging import (
    log_armed as _log_reset_armed,
    log_fired as _log_reset_fired,
    log_pending as _log_reset_pending,
    log_timeout as _log_reset_timeout,
)
from utils.logger import get_logger

_log = get_logger("drivetrain")


class CommandSwerveDrivetrain(Subsystem, TunerSwerveDrivetrain):
    """
    Class that extends the Phoenix 6 SwerveDrivetrain class and implements
    Subsystem so it can easily be used in command-based projects.

    Generated by the 2026 Tuner X Swerve Project Generator
    https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
    """

    _SIM_LOOP_PERIOD: units.second = 0.004  # 4 ms

    _BLUE_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(0)
    """Blue alliance sees forward as 0 degrees (toward red alliance wall)"""
    _RED_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(180)
    """Red alliance sees forward as 180 degrees (toward blue alliance wall)"""

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants: Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:  swerve.SwerveDrivetrainConstants
        :param modules:              Constants for each specific module
        :type modules:               list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants:        Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:         swerve.SwerveDrivetrainConstants
        :param odometry_update_frequency:   The frequency to run the odometry loop. If
                                            unspecified or set to 0 Hz, this is 250 Hz on
                                            CAN FD, and 100 Hz on CAN 2.0.
        :type odometry_update_frequency:    units.hertz
        :param modules:                     Constants for each specific module
        :type modules:                      list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        odometry_standard_deviation: tuple[float, float, float],
        vision_standard_deviation: tuple[float, float, float],
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants:        Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:         swerve.SwerveDrivetrainConstants
        :param odometry_update_frequency:   The frequency to run the odometry loop. If
                                            unspecified or set to 0 Hz, this is 250 Hz on
                                            CAN FD, and 100 Hz on CAN 2.0.
        :type odometry_update_frequency:    units.hertz
        :param odometry_standard_deviation: The standard deviation for odometry calculation
                                            in the form [x, y, theta]T, with units in meters
                                            and radians
        :type odometry_standard_deviation:  tuple[float, float, float]
        :param vision_standard_deviation:   The standard deviation for vision calculation
                                            in the form [x, y, theta]T, with units in meters
                                            and radians
        :type vision_standard_deviation:    tuple[float, float, float]
        :param modules:                     Constants for each specific module
        :type modules:                      list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0: None,
        arg1: None,
        arg2: None,
        arg3: None,
        /,
    ) -> None: ...

    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0=None,
        arg1=None,
        arg2=None,
        arg3=None,
    ):
        Subsystem.__init__(self)
        TunerSwerveDrivetrain.__init__(
            self, drivetrain_constants, arg0, arg1, arg2, arg3
        )

        self._sim_notifier: Notifier | None = None
        self._last_sim_time: units.second = 0.0

        self._has_applied_operator_perspective = False
        """Keep track if we've ever applied the operator perspective before or not"""

        # Swerve requests to apply during SysId characterization
        self._translation_characterization = swerve.requests.SysIdSwerveTranslation()
        self._steer_characterization = swerve.requests.SysIdSwerveSteerGains()
        self._rotation_characterization = swerve.requests.SysIdSwerveRotation()

        self._sys_id_routine_translation = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Reduce dynamic voltage to 4 V to prevent brownout
                stepVoltage=4.0,
                # Log state with SignalLogger class
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdTranslation_State", SysIdRoutineLog.stateEnumToString(state)
                )
                and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._translation_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )
        """SysId routine for characterizing translation. This is used to find PID gains for the drive motors."""

        self._sys_id_routine_steer = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Log state with SignalLogger class
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdSteer_State", SysIdRoutineLog.stateEnumToString(state)
                )
                and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._steer_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )
        """SysId routine for characterizing steer. This is used to find PID gains for the steer motors."""

        self._sys_id_routine_rotation = SysIdRoutine(
            SysIdRoutine.Config(
                # This is in radians per second squared, but SysId only supports "volts per second"
                rampRate=math.pi / 6,
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Use default timeout (10 s)
                # Log state with SignalLogger class
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdSteer_State", SysIdRoutineLog.stateEnumToString(state)
                )
                and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: (
                    # output is actually radians per second, but SysId only supports "volts"
                    self.set_control(
                        self._rotation_characterization.with_rotational_rate(output)
                    ),
                    # also log the requested output for SysId
                    SignalLogger.write_double("Rotational_Rate", output),
                )
                and None,
                lambda log: None,
                self,
            ),
        )
        """
        SysId routine for characterizing rotation.
        This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
        See the documentation of swerve.requests.SysIdSwerveRotation for info on importing the log to SysId.
        """

        self._sys_id_routine_to_apply = self._sys_id_routine_translation
        """The SysId routine to test"""

        # --- Limelight MegaTag2 odometry ---
        # Continuous soft-correction counter: gates vision_pose_correct()
        # inside periodic() so we can dial back frequency on overruns.
        self._vision_correct_loop_counter = 0
        # Deferred one-shot hard reset (B button). Armed by
        # vision_pose_reset_request(), serviced in periodic() once a
        # camera actually sees tags (up to VISION_RESET_TIMEOUT).
        self._vision_reset_pending = False
        self._vision_reset_deadline = 0.0

        # PathPlanner AutoBuilder configuration
        self._path_apply_robot_speeds = swerve.requests.ApplyRobotSpeeds()
        try:
            config = RobotConfig.fromGUISettings()
            AutoBuilder.configure(
                lambda: self.get_state().pose,
                lambda pose: self.reset_pose(pose),
                lambda: self.get_state().speeds,
                lambda speeds, feedforwards: self.set_control(
                    self._path_apply_robot_speeds
                    .with_speeds(speeds)
                    .with_wheel_force_feedforwards_x(
                        feedforwards.robotRelativeForcesXNewtons
                    )
                    .with_wheel_force_feedforwards_y(
                        feedforwards.robotRelativeForcesYNewtons
                    )
                ),
                PPHolonomicDriveController(
                    PIDConstants(10.0, 0.0, 0.0),
                    PIDConstants(7.0, 0.0, 0.0),
                ),
                config,
                lambda: (
                    DriverStation.getAlliance()
                    == DriverStation.Alliance.kRed
                ),
                self,
            )
        except Exception as e:
            _log.error(f"Failed to load PathPlanner config: {e}")

        if utils.is_simulation():
            self._start_sim_thread()

    def apply_request(
        self, request: Callable[[], swerve.requests.SwerveRequest]
    ) -> Command:
        """
        Returns a command that applies the specified control request to this swerve drivetrain.

        :param request: Lambda returning the request to apply
        :type request: Callable[[], swerve.requests.SwerveRequest]
        :returns: Command to run
        :rtype: Command
        """
        return self.run(lambda: self.set_control(request()))

    def sys_id_quasistatic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Quasistatic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.

        :param direction: Direction of the SysId Quasistatic test
        :type direction: SysIdRoutine.Direction
        :returns: Command to run
        :rtype: Command
        """
        return self._sys_id_routine_to_apply.quasistatic(direction)

    def sys_id_dynamic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Dynamic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.

        :param direction: Direction of the SysId Dynamic test
        :type direction: SysIdRoutine.Direction
        :returns: Command to run
        :rtype: Command
        """
        return self._sys_id_routine_to_apply.dynamic(direction)

    def periodic(self):
        # Periodically try to apply the operator perspective.
        # If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
        # This allows us to correct the perspective in case the robot code restarts mid-match.
        # Otherwise, only check and apply the operator perspective if the DS is disabled.
        # This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
        if not self._has_applied_operator_perspective or DriverStation.isDisabled():
            alliance_color = DriverStation.getAlliance()
            if alliance_color is not None:
                self.set_operator_perspective_forward(
                    self._RED_ALLIANCE_PERSPECTIVE_ROTATION
                    if alliance_color == DriverStation.Alliance.kRed
                    else self._BLUE_ALLIANCE_PERSPECTIVE_ROTATION
                )
                self._has_applied_operator_perspective = True

        # --- MegaTag2: always send heading to every Limelight ---
        # Cheap (6 doubles per camera to NT). Must run every loop so
        # MegaTag2 can break the single-tag PnP ambiguity.
        yaw_deg = self.get_pose().rotation().degrees()
        for cam in CON_VISION["cameras"].values():
            set_robot_orientation(cam["nt_name"], yaw_deg)

        # --- Continuous soft correction ---
        self._vision_correct_loop_counter += 1
        if self._vision_correct_loop_counter >= VISION_POSE_CORRECT_PERIOD_LOOPS:
            self._vision_correct_loop_counter = 0
            self.vision_pose_correct()

        # --- Deferred one-shot hard reset (B button) ---
        if self._vision_reset_pending:
            if Timer.getFPGATimestamp() > self._vision_reset_deadline:
                self._vision_reset_pending = False
                _log_reset_timeout(VISION_RESET_TIMEOUT)
                return

            odom_pose = self.get_pose()
            _log_reset_pending(odom_pose)

            best = self._vision_pose_read_mt1()
            if best is not None:
                cam_key, estimate = best
                # Full override: replace X, Y, AND yaw with MT1's pose.
                # We do NOT keep the current gyro heading -- the whole
                # point of the hard reset is to escape gyro drift, and
                # leaving the wrong yaw in place means soft correction
                # will pull right back to the bad spot within a few
                # loops. Driver field-centric "forward" will visibly
                # jump on a B press; that is intentional.
                self.reset_pose(estimate.pose)
                self._vision_reset_pending = False
                _log_reset_fired(cam_key, odom_pose, estimate, estimate.pose)

    def _vision_pose_read_mt1(self) -> tuple[str, "object"] | None:
        """
        Read MegaTag1 pose from every configured Limelight and return
        the best (camera_key, PoseEstimate) tuple, or None if no camera
        has enough tags.

        Used by the B-button hard reset. We deliberately use MT1 (pure
        AprilTag PnP, no gyro fusion) here so the reset is independent
        of the gyro -- this is the only way to escape a gyro-MT2
        feedback loop where odom and MT2 have converged on a wrong but
        self-consistent pose.

        Requires `tag_count >= VISION_MT1_MIN_TAGS` (default 2) because
        single-tag MT1 has unresolved PnP ambiguity and could snap odom
        to a mirrored position.

        "Best" = most tags, tie-broken by larger avg_tag_area.
        """
        best_key: str | None = None
        best_estimate = None
        for key, cam in CON_VISION["cameras"].items():
            estimate = get_bot_pose_estimate_wpi_blue_megatag1(cam["nt_name"])
            if estimate is None or estimate.tag_count < VISION_MT1_MIN_TAGS:
                continue
            if best_estimate is None:
                best_key, best_estimate = key, estimate
                continue
            if (
                estimate.tag_count > best_estimate.tag_count
                or (
                    estimate.tag_count == best_estimate.tag_count
                    and estimate.avg_tag_area > best_estimate.avg_tag_area
                )
            ):
                best_key, best_estimate = key, estimate
        if best_estimate is None:
            return None
        return best_key, best_estimate

    def vision_pose_correct(self) -> None:
        """
        Soft pose correction. For every Limelight that currently sees
        tags, feed its bot-pose estimate into the WPILib pose estimator
        via add_vision_measurement(). Safe to call every loop; safe to
        call from auton named commands (no subsystem requirements).

        Which estimate is used depends on VISION_POSE_CORRECT_MODE:
          "mt2" -- MegaTag2 (gyro-fused). Accepts single-tag readings
                   because the gyro disambiguates PnP.
          "mt1" -- MegaTag1 (pure AprilTag PnP). Requires at least
                   VISION_MT1_MIN_TAGS tags per camera; single-tag MT1
                   is rejected because PnP is ambiguous.

        Honors the VISION_POSE_CORRECT_ENABLED kill switch so it can be
        flipped off between matches without rebuilding the binding tree.
        The B-button hard reset bypasses this flag intentionally.
        """
        if not VISION_POSE_CORRECT_ENABLED:
            return

        for cam in CON_VISION["cameras"].values():
            estimate = self._read_vision_estimate_for_mode(cam["nt_name"])
            if estimate is None:
                continue
            self.add_vision_measurement(
                estimate.pose, estimate.timestamp_seconds
            )

        maybe_log_vision_correct(self.get_pose())

    def _read_vision_estimate_for_mode(self, nt_name: str):
        """
        Return the bot-pose estimate for one camera based on
        VISION_POSE_CORRECT_MODE, or None if the chosen source has
        insufficient tags for this mode.
        """
        if VISION_POSE_CORRECT_MODE == "mt1":
            estimate = get_bot_pose_estimate_wpi_blue_megatag1(nt_name)
            if estimate is None or estimate.tag_count < VISION_MT1_MIN_TAGS:
                return None
            return estimate
        # Default / "mt2": accept any tag count >= 1 (gyro disambiguates).
        estimate = get_bot_pose_estimate_wpi_blue_megatag2(nt_name)
        if estimate is None or estimate.tag_count < 1:
            return None
        return estimate

    def vision_pose_reset_request(self) -> None:
        """
        Arm a one-shot hard pose reset. Serviced in periodic() on the
        next loop that any Limelight actually sees tags, up to
        VISION_RESET_TIMEOUT. Driver escape hatch when the Kalman
        estimate has drifted too far for soft corrections to recover.
        """
        self._vision_reset_pending = True
        self._vision_reset_deadline = (
            Timer.getFPGATimestamp() + VISION_RESET_TIMEOUT
        )
        _log_reset_armed(VISION_RESET_TIMEOUT)

    def request_hub_reset(self) -> None:
        """Hard-reset odometry to the front of the alliance Hub."""
        alliance = DriverStation.getAlliance()
        if alliance == DriverStation.Alliance.kBlue:
            key = "Blue"
        else:
            key = "Red"
        pose_cfg = HUB_RESET_POSES[key]
        pose = Pose2d(pose_cfg["x"], pose_cfg["y"],
                      Rotation2d.fromDegrees(pose_cfg["heading"]))
        self.reset_pose(pose)
        _log.warning(
            f"HUB RESET ({key}): "
            f"x={pose_cfg['x']:.2f} y={pose_cfg['y']:.2f} "
            f"heading={pose_cfg['heading']:.0f}"
        )

    def _start_sim_thread(self):
        def _sim_periodic():
            current_time = utils.get_current_time_seconds()
            delta_time = current_time - self._last_sim_time
            self._last_sim_time = current_time

            # use the measured time delta, get battery voltage from WPILib
            self.update_sim_state(delta_time, RobotController.getBatteryVoltage())

        # Run simulation at a faster rate so PID gains behave more reasonably
        self._last_sim_time = utils.get_current_time_seconds()
        self._sim_notifier = Notifier(_sim_periodic)
        self._sim_notifier.startPeriodic(self._SIM_LOOP_PERIOD)

    def get_pose(self) -> Pose2d:
        """Return the current estimated robot pose from odometry."""
        return self.get_state().pose

    def reset_pose(self, pose: Pose2d) -> None:
        """Reset the odometry to a given pose."""
        self.reset_rotation(pose.rotation())
        self.reset_translation(pose.translation())

    def add_vision_measurement(
        self,
        vision_robot_pose: Pose2d,
        timestamp: units.second,
        vision_measurement_std_devs: tuple[float, float, float] | None = None,
    ):
        """
        Adds a vision measurement to the Kalman Filter. This will correct the
        odometry pose estimate while still accounting for measurement noise.

        Note that the vision measurement standard deviations passed into this method
        will continue to apply to future measurements until a subsequent call to
        set_vision_measurement_std_devs or this method.

        :param vision_robot_pose:           The pose of the robot as measured by the vision camera.
        :type vision_robot_pose:            Pose2d
        :param timestamp:                   The timestamp of the vision measurement in seconds.
        :type timestamp:                    second
        :param vision_measurement_std_devs: Standard deviations of the vision pose measurement
                                            in the form [x, y, theta]T, with units in meters
                                            and radians.
        :type vision_measurement_std_devs:  tuple[float, float, float] | None
        """
        TunerSwerveDrivetrain.add_vision_measurement(
            self,
            vision_robot_pose,
            utils.fpga_to_current_time(timestamp),
            vision_measurement_std_devs
        )

    def sample_pose_at(self, timestamp: units.second) -> Pose2d | None:
        """
        Return the pose at a given timestamp, if the buffer is not empty.

        :param timestamp: The timestamp of the pose in seconds.
        :type timestamp: second
        :returns: The pose at the given timestamp (or None if the buffer is empty).
        :rtype: Pose2d | None
        """
        return TunerSwerveDrivetrain.sample_pose_at(self, utils.fpga_to_current_time(timestamp))
